export const CANT_DELETE_CATEGORY =
  'CANNOT_DELETE_CATEGORY_WHILE_SOME_PRODUCT_EXIST_IN_THIS';
export const CATEGORY_EXIST = 'SUCH_CATEGORY_ALREADY_EXIST';
export const USER_EXIST = 'SUCH_USER_ALREADY_EXIST';
export const MUST_BE_SPECIFIED = 'AN_EXISTING_CATEGORY_MUST_BE_SPECIFIED';
export const CATEGORY_IS_HIDE = 'CATEGORY_IS_HIDE';
export const USER_DIDNT_FIND = 'SUCH_USER_DIDNT_FIND';
export const INVALID_PASSWORD = 'PASSWORD_IS_WRONG';
export const UNAUTORIZED = 'UNAUTORIZED';
export const VALIDATION_FAILED = 'VALIDATION_FAILED';
export const PRODUCT_IS_NOT_EXIST = 'PRODUCT_IS_NOT_EXIST';
export const PRODUCT_NAME_IS_TOO_SHORT = 'PRODUCT_NAME_IS_TOO_SHORT';
export const CATEGORY_NAME_IS_TOO_SHORT = 'CATEGORY_NAME_IS_TOO_SHORT';
export const CANT_DELETE_PRODUCT_IMAGE = 'CANT_DELETE_PRODUCT_IMAGE';
export const BAD_TOKEN = 'BAD_TOKEN';
export const UNKNOWN_ERROR = 'UNKNOWN_ERROR_OCCURED';
export const CREDENTIALS_WAS_NOT_RECOGNIZED = 'CREDENTIALS_WAS_NOT_RECOGNIZED';
export const WRONG_EMAIL = 'LINK ARE WRONG TO THIS EMAIL';
export const PRODUCT_IN_FAVORITES_IS_NOT_FOUND =
  'PRODUCT_IN_FAVORITES_IS_NOT_FOUND_IN_DATABASE';
export const ADDRESS_IS_TOO_SHORT = 'ADDRESS_IS_TOO_SHORT';
export const INVALID_COORDINATE_POSITION = 'INVALID_COORDINATE_POSITION';
